/* Generated by           cobc 3.2.0 */
/* Generated from         samples/sample-ncurses-window.cbl */
/* Generated at           Mar 14 2025 18:55:05 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -o bin-samples/sample-ncurses-window.c samples/sample-ncurses-window.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x10,   3,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x21,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {18, (cob_u8_ptr)"INITIALIZE-NCURSES", &a_1};
static const cob_field c_2	= {14, (cob_u8_ptr)"UNLOAD-NCURSES", &a_1};

