/* Generated by           cobc 3.2.0 */
/* Generated from         samples/sample-ncurses-window.cbl */
/* Generated at           Mar 14 2025 18:55:05 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -o bin-samples/sample-ncurses-window.c samples/sample-ncurses-window.cbl */

/* Program local variables for 'sample-ncurses-window' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call pointers */
static cob_call_union	call_NCURSES__UTIL;
static cob_call_union	call_NCURSES__WINDOW;

/* Call parameters */
cob_field		*cob_procedure_params[5];

/* Perform frame stack */
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[3] __attribute__((aligned));	/* WINDOW-WIDTH */
static cob_u8_t	b_18[3] __attribute__((aligned));	/* WINDOW-HEIGHT */
static cob_u8_t	b_19[3] __attribute__((aligned));	/* WINDOW-X */
static cob_u8_t	b_20[3] __attribute__((aligned));	/* WINDOW-Y */
static cob_u8_t	b_21[1] __attribute__((aligned));	/* SHADOW-ENABLED */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {3, b_17, &a_2};	/* WINDOW-WIDTH */
static cob_field f_18	= {3, b_18, &a_2};	/* WINDOW-HEIGHT */
static cob_field f_19	= {3, b_19, &a_2};	/* WINDOW-X */
static cob_field f_20	= {3, b_20, &a_2};	/* WINDOW-Y */
static cob_field f_21	= {1, b_21, &a_3};	/* SHADOW-ENABLED */

/* End of fields */

